apiVersion: v1
kind: Service
metadata:
  name: simpleapp-service
spec:
  selector:
    app: simpleapp-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31001  
  type: NodePort
