apiVersion: v1
kind: Pod
metadata:
  name: podnode1
  labels:
    app: podnode1
spec:
  nodeSelector:
   
    cloudethix-k8s-01: worker-1
  containers:
    - name: podnode1
      image: vivekmore5292/cloudethix_master_nginx_vivek:v1
      command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']